const colors = {
  light: {
    text: "#0F172A",
    tint: "#2563EB",
    background: "#F8FAFF",
    foreground: "#0F172A",
    card: "#FFFFFF",
    cardForeground: "#0F172A",
    primary: "#2563EB",
    primaryForeground: "#FFFFFF",
    secondary: "#EFF6FF",
    secondaryForeground: "#1D4ED8",
    muted: "#F1F5F9",
    mutedForeground: "#64748B",
    accent: "#DBEAFE",
    accentForeground: "#1E40AF",
    destructive: "#EF4444",
    destructiveForeground: "#FFFFFF",
    success: "#10B981",
    successForeground: "#FFFFFF",
    warning: "#F59E0B",
    warningForeground: "#FFFFFF",
    border: "#E2E8F0",
    input: "#E2E8F0",
    surface: "#FFFFFF",
    overlay: "rgba(15,23,42,0.5)",
  },
  dark: {
    text: "#F8FAFF",
    tint: "#3B82F6",
    background: "#0F172A",
    foreground: "#F8FAFF",
    card: "#1E293B",
    cardForeground: "#F8FAFF",
    primary: "#3B82F6",
    primaryForeground: "#FFFFFF",
    secondary: "#1E3A5F",
    secondaryForeground: "#93C5FD",
    muted: "#1E293B",
    mutedForeground: "#94A3B8",
    accent: "#1E3A5F",
    accentForeground: "#93C5FD",
    destructive: "#EF4444",
    destructiveForeground: "#FFFFFF",
    success: "#10B981",
    successForeground: "#FFFFFF",
    warning: "#F59E0B",
    warningForeground: "#FFFFFF",
    border: "#334155",
    input: "#334155",
    surface: "#1E293B",
    overlay: "rgba(0,0,0,0.7)",
  },
  radius: 12,
};

export default colors;
